export const projects = [
  {
    title: 'CoDebug',
    description: "Development, as a team, of a question and answer platform for programming students",
    image: '/images/codebug.png',
    tags: ['Redux', 'Express', 'React', 'Node.js'],
    source: 'https://github.com/Codebug-Henry/Co-debug',
    visit: 'https://codebug-ten.vercel.app/',
    id: 0,
  },
  {
    title: 'Finance App - Alkemy Challenge',
    description: 'Desing and develop a FullStack App where users can manage their transactions. Alkemy Full-Stack JS Challenge.',
    image: '/images/finance.png',
    tags: ['React', 'Redux', 'Express', 'Node.js', 'Sequelize', 'JWT'],
    source: 'https://github.com/Sandotcom/Alkemy-Challenge',
    id: 1,
  },
  {
    title: 'YouTube Backend clone',
    description: "The purpuse of this project is try to recreate the YouTube Back-end structure.",
    image: '/images/youtube2.png',
    tags: ['Node.js', 'Express', 'MongoDB', 'JWT'],
    source: 'https://github.com/Sandotcom/YouTube-Clone',
    id: 2,
  },
  {
    title: 'Auth project',
    description: "Setup of a Backend structure that allows users to registrer or sign in to your project. It was developed with JWT and Google OAuth",
    image: '/images/auth.png',
    tags: ['Node.js', 'Express', 'MongoDB', 'JWT', 'Google OAuth'],
    source: 'https://github.com/Sandotcom/Auth',
    id: 3,
  },
  {
    title: 'Dogs API',
    description: "Design and develop an App, getting the info from an API of dogs. This SPA includes: searches, filtering, ordering and creation.",
    image: '/images/dogs.png',
    tags: ['React', 'Redux', 'Express', 'Node.js'],
    source: 'https://github.com/Sandotcom/PI-Dogs',
    visit: 'https://pi-dogs-sandotcom.vercel.app/home',
    id: 4,
  },
  {
    title: 'Portfolio',
    description: "This site was built with Next.js to learn about it",
    image: '/images/portfolio.png',
    tags: ['React', 'Next.js', 'Styled Components'],
    source: 'https://github.com/Sandotcom/portfolio',
    visit: 'https://sandotcom.vercel.app/',
    id: 5,
  },
];